services:
  postgres_db:
    image: postgres:16-alpine
    container_name: streampixel_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: streampixel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
      target: production
    container_name: streampixel_backend
    restart: always
    ports:
      - '5000:5000'
      - '8800-9100:8800-9100'
    volumes:
      - streampixel_storage:/opt/streampixel/storage
    environment:
      - NODE_ENV=production
      - STORAGE_PATH=/opt/streampixel/storage
      - DATABASE_URL=postgresql://postgres:postgres123@postgres_db:5432/streampixel?schema=public
      - CORS_ORIGIN=http://13.201.4.220:3000
    env_file:
      - ../../.env
    depends_on:
      postgres_db:
        condition: service_healthy

  frontend:
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
      target: production
      args:
        NEXT_PUBLIC_API_URL: http://13.201.4.220:5000/api/v1
    container_name: streampixel_frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ../../.env
    depends_on:
      - backend

volumes:
  postgres_data:
  streampixel_storage:
